services:
  ui:
    container_name: "StitchSketch-UI"
    ports:
      - "8009:8000"
    build:
      context: ./src/ui
      dockerfile: ui.Dockerfile
    env_file: .env

  api_gateway:
    container_name: "StitchSketch-API"
    ports:
      - "8089:8089"
    build:
      context: ./src/api_gateway
      dockerfile: api_gateway.Dockerfile
    env_file: .env

  keycloak:
    container_name: "StitchSketch-IAM"
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-users.json:/opt/keycloak/conf/keycloak-users.json
      - ./keycloak-realm.json:/opt/keycloak/conf/keycloak-realm.json
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=${KC_DB:-postgres}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
    build:
      context: ./src/keycloak
      dockerfile: keycloak.Dockerfile
    env_file: .env

  postgres:
    container_name: "StitchSketch-PG"
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: .env
