services:
  suitecrm:
    image: bitnami/suitecrm:8
    container_name: suitecrm
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - SUITECRM_DATABASE_HOST=db
      - SUITECRM_DATABASE_PORT_NUMBER=3306
      - SUITECRM_DATABASE_NAME=${DB_NAME}
      - SUITECRM_DATABASE_USER=${DB_USER}
      - SUITECRM_DATABASE_PASSWORD=${DB_PASSWORD}
    ports:
      - 80:8080
      - 443:8443
    depends_on:
      - db
    volumes:
      - ./suitecrm_data:/bitnami/suitecrm

  db:
    hostname: db
    image: bitnami/mariadb:latest
    container_name: suitecrm_db
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/bitnami/mariadb
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./fe:/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD= ${DB_ROOT_PASSWORD}
    depends_on:
      - suitecrm

  chat:
    image: mattermost/mattermost-preview:latest
    container_name: mattermost-chat
    ports:
      - "8065:8065" # Default Mattermost port
    environment:
      - MM_USERNAME={ MM_USERNAME }
      - MM_EMAIL={ MM_EMAIL }
      - MM_PASSWORD={ MM_PASSWORD }
      - MM_TEAM_NAME={ MM_TEAM_NAME }
    volumes:
      - mattermost_data:/mattermost/data

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - metabase_data:/metabase-data

volumes:
  suitecrm_data:
  db_data:
  metabase_data:
  mattermost_data:
