services:
  suitecrm:
    image: bitnami/suitecrm:8
    container_name: suitecrm
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - SUITECRM_DATABASE_HOST=db
      - SUITECRM_DATABASE_PORT_NUMBER=3306
      - SUITECRM_DATABASE_NAME=${DB_NAME}
      - SUITECRM_DATABASE_USER=${DB_USER}
      - SUITECRM_DATABASE_PASSWORD=${DB_PASSWORD}
    ports:
      - 80:8080
      - 443:8443
    depends_on:
      - db
    volumes:
      - ./suitecrm_data:/bitnami/suitecrm

  db:
    image: bitnami/mariadb:latest
    container_name: suitecrm_db
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/bitnami/mariadb

volumes:
  suitecrm_data:
  db_data:
