services:
  ui:
    build:
      context: ./src
      dockerfile: ui.Dockerfile
    restart: always
    ports:
      - "8009:8009"

  api_gateway:
    build:
      context: ./src
      dockerfile: api_gateway.Dockerfile
    restart: always
    ports:
      - "8089:8089"
