services:
  ui:
    container_name: "StitchSketch-UI"
    hostname: stitchsketch-dev
    ports:
      - "8009:8000"
    build:
      context: ./src/ui
      dockerfile: ui.Dockerfile
    volumes:
      - ./media:/app/ui/media
    env_file: .env

  postgres:
    container_name: "StitchSketch-PG"
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: .env
